carts/urls.py
from django.conf.urls import url

from .views import CartView,add_to_cart,remove_from_cart

urlpatterns = [
    url(r'^$', CartView.as_view(), name='cart_view'),
    url(r'^add/(?P<slug>[\w-]+)/$', add_to_cart, name='add_to_cart'),
    url(r'^remove/(?P<id>\d+)/$', remove_from_cart, name='remove_from_cart'),

    # url(r'^catalog/(?P<slug>[w]+)$', DetailView.as_view(), name='detail')
]

catalog/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import HomeView,CatalogView,CatalogDetailView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^detail/$', CatalogDetailView.as_view(), name='detail'),
    url(r'^catalog/$', CatalogView.as_view(), name='catalog'),
    # url(r'^catalog/(?P<slug>[w]+)$', DetailView.as_view(), name='detail')
]

fabulousd/urls.py
from django.conf import settings
from django.conf.urls import include,url
from django.contrib import admin
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include("carts.urls", namespace='carts')),
    url(r'^order/', include("orders.urls", namespace='orders')),
    url(r'^', include("products.urls", namespace='products')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import include,url
from .views import check_out,OrderListView

urlpatterns = [
    url(r'^check_out/', check_out, name='check_out'),
    url(r'^', OrderListView.as_view(), name='order_list'),
]

products/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import HomeView,ProductListView,ProductDetailView,search_view

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^s/$', search_view, name='search'),
    url(r'^products/$', ProductListView.as_view(), name='product_list'),
    url(r'^products/(?P<slug>[\w-]*)/$', ProductDetailView.as_view(), name='product_detail'),
    # url(r'^products/$', CatalogDetailView.as_view(), name='detail'),
    # url(r'^catalog/$', CatalogView.as_view(), name='catalog'),
    # url(r'^catalog/(?P<slug>[w]+)$', DetailView.as_view(), name='detail')
]

carts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from products.models import Product,Variation

class CartItem(models.Model):
	cart = models.ForeignKey('Cart', null=True)
	product = models.ForeignKey(Product)
	variations = models.ManyToManyField(Variation, blank=True)
	quantity = models.IntegerField(default=1)
	line_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
	notes = models.TextField(null=True, blank=True)
	# Create your models here.

	def __unicode__(self):
		try:
			return str(self.cart.id)
		except:
			return self.product.name

	def __str__(self):
		try:
			return str(self.cart.id)
		except:
			return self.product.name

class Cart(models.Model):
	total_price = models.DecimalField(max_digits=9,decimal_places=2, default=0.00)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	is_active = models.BooleanField(default=True)


	def __unicode__(self):
		return "Card ID is : {0}".format(self.id)

	def __str__(self):
		return "Card ID is : {0}".format(self.id)

catalog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.


class Category(models.Model):
	name = models.CharField(max_length=50)
	slug = models.SlugField(max_length=100, unique=True, help_text='Unique value for product page URL, created from name.')
	description = models.TextField()
	is_active = models.BooleanField(default=True)
	meta_keywords = models.CharField('Meta Keywords', max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag')
	meta_description = models.CharField('Meta Description', max_length=225, help_text='Content for description meta tag')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'categories'
		ordering = ['-created_at']
		verbose_name_plural = 'Categories'

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('catalog_category', (), { 'category_slug': self.slug })

class Product(models.Model):
	name = models.CharField(max_length=50, unique=True)
	slug = models.SlugField(max_length=100, unique=True, help_text='Unique value for product page URL, created from name.')
	brand = models.CharField(max_length=50)
	sku = models.CharField(max_length=50)
	price = models.DecimalField(max_digits=9,decimal_places=2)
	old_price = models.DecimalField(max_digits=9,decimal_places=2, blank=True,default=0.00)
	image = models.CharField(max_length=50)
	is_active = models.BooleanField(default=True)
	is_bestseller = models.BooleanField(default=False)
	is_featured = models.BooleanField(default=False)
	quantity = models.IntegerField()
	description = models.TextField()
	meta_keywords = models.CharField(max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag')
	meta_description = models.CharField(max_length=255, help_text='Content for description meta tag')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	categories = models.ManyToManyField(Category)

	class Meta:
		db_table = 'products'
		ordering = ['-created_at']

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("catalog:detail", kwargs={"slug": self.slug})

	def sale_price(self):
		if self.old_price > self.price:
			return self.price
		else:
			return None

products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse

from django.db import models

# Create your models here.
class Product(models.Model):
	name = models.CharField(max_length=50, unique=True)
	slug = models.SlugField(max_length=100, unique=True, help_text='Unique value for product page URL, created from name.')
	price = models.DecimalField(max_digits=9,decimal_places=2)
	sale_price = models.DecimalField(max_digits=9,decimal_places=2)
	is_active = models.BooleanField(default=True)
	is_new_arrival = models.BooleanField(default=False)
	is_best_seller = models.BooleanField(default=False)
	is_featured = models.BooleanField(default=False)
	description = models.TextField()
	# image = models.ImageField(upload_to='products/images',null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	# categories = models.ManyToManyField(Category)

	class Meta:
		db_table = 'products'
		ordering = ['-created_at']
		unique_together = ('name', 'slug')

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("products:product_detail", kwargs={"slug": self.slug})

	def get_price(self):
		return self.price
		# if self.old_price > self.price:
		# 	return self.price
		# else:
		# 	return None

class ProductImage(models.Model):
	product = models.ForeignKey(Product)
	image = models.ImageField(upload_to='products/images',null=True)
	is_featured = models.BooleanField(default=False)
	is_featured = models.BooleanField(default=False)
	is_thumbnail = models.BooleanField(default=False)
	updated_at = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.product.name

	def __str__(self):
		return self.product.name

class VariationManager(models.Manager):
	def all(self):
		return super(VariationManager,self).filter(is_active=True)

	def sizes(self):
		return self.all().filter(category='size')

	def colors(self):
		return self.all().filter(category='color')

	def packages(self):
		return self.all().filter(category='package')

VAR_CATEGORIES = (
	('size','size'),
	('color','color'),
	('package','package')
	)
class Variation(models.Model):
	product = models.ForeignKey(Product)
	category = models.CharField(max_length=20, choices=VAR_CATEGORIES, default='size')
	title = models.CharField(max_length=100)
	image = models.ForeignKey(ProductImage, null=True, blank=True)
	price = models.DecimalField(max_digits=9,decimal_places=2,null=True,blank=True)
	is_active = models.BooleanField(default=True)
	updated_at = models.DateTimeField(auto_now=True)
	# sku (stock keeping unit)

	objects = VariationManager()

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

catalog/forms.py
from django import forms
from .models import Product

class ProductAdminForm(forms.ModelForm):	
	class Meta:
		model = Product
		exclude = ('created_at', 'updated_at',)


	def clean_price(self):
		if self.cleaned_data['price'] <= 0:
			raise forms.ValidationError('Price must be greater than zero.')
		return self.cleaned_data['price']

catalog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from .models import Product,Category

# Create your views here.
from django.views.generic import TemplateView,ListView,DetailView

class HomeView(TemplateView):
	template_name = 'index.html'
	queryset = Product.objects.all()
	model = Product

	def get_context_data(self, **kwargs):
	    context = super(HomeView, self).get_context_data(**kwargs)
	    context['products'] = self.queryset
	    return context

	# def get_context_data(self)CatalogView


class CatalogView(ListView):
	model = Product
	template_name = 'catalog.html'
	page_title = 'Cloths and other designer wears'

	def get_context_data(self, **kwargs):
	    # Call the base implementation first to get a context
	    context = super(CatalogView, self).get_context_data(**kwargs)
	    # Add in the publisher
	    # context['products'] = self.name
	    context['title'] = self.page_title

	    return context


class CatalogDetailView(DetailView):
	template_name = 'detail.html'
	model = Product

	def get_context_data(self, *args, **kwargs):
	    context = super(CatalogDetailView, self).get_context_data(*args, **kwargs)
	    context['now'] = timezone.now()
	    return context

	# def get_slug_field(self, **kwargs):
	# 	pass

templates/base.html
<!DOCTYPE HTML>
{% load staticfiles %}
{% load i18n %}
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<title>{% block title %} {% endblock %}</title>
	<link href='https://fonts.googleapis.com/css?family=Lato:400,100,700' rel='stylesheet' type='text/css'/>
	<link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fancybox.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.transitions.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}" media="all"/>
	{% block style %} {% endblock %}

</head>
<body>
	<div class="wrap">
		<div id="header">
			<div class="top-header">
				<div class="container">
					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="top-support">
								<ul class="list-inline">
									<li><a href="#" class="top-support-link">Help </a></li>
									<li><a href="#" class="top-support-link">Services</a></li>
									<li><a href="#" class="top-support-link">USD</a></li>
									<li><a href="#" class="top-support-link"><img src="{% static 'images/home12/icon-flag.png' %}" alt="" /></a></li>
								</ul>
							</div>
						</div>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="top-info">
								<ul class="list-inline text-right">
									<li><a href="#" class="top-info-link"><i class="fa fa-user"></i> My Account</a></li>
									<li><a href="#" class="top-info-link"><i class="fa fa-heart"></i> Wishlist</a></li>
									<li><a href="#" class="top-info-link"><i class="fa fa-refresh"></i> Compare</a></li>
									<li><a href="#" class="top-info-link"><i class="fa fa-sign-out"></i> Check out</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="main-header">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="logo">
								<a href="{% url 'products:home' %}"><h2 style="color:#fff;">FabulousD</h2></a>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="phone-info">
								<label>Call Us Now</label>
								<h2 class="phone-number">Toll free : +2348186737195</h2>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="top-cart">
								<h2><a href="{% url 'carts:cart_view' %}">shopping Cart</a></h2>
								<p>{{ request.session.items_total }} Item(s) - ${{ request.session.total_price }}</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="header-nav">
				<div class="container">
					<div class="row">
						<div class="col-md-9 col-sm-9 col-xs-12">
							<div class="main-nav">
								<ul>
									<li><a href="{% url 'products:home' %}">Home </a></li>
									<li class="menu-item-has-children"><a href="">Mens</a></li>
									<li class="menu-item-has-children"><a href="">Womens</a></li>
									<li class="menu-item-has-children"><a href="">Kids</a></li>
									<li class="menu-item-has-children"><a href="">Accessories</a></li>
									<li><a href="{% url 'products:product_list' %}">Products</a></li>
									<li><a href="#">Contact</a></li>
								</ul>
							</div>
						</div>
						<div class="col-md-3 col-sm-3 col-xs-12">
							<form class="navbar-form" role="search" action='/s/'>
								<div class='form-group'>
									<input type="text" class="form-control" name="q" placeholder="Enter your keyword...">
									<button type="submit" class="btn btn-default">Search</button>
								</div>
							</form>
							<!-- <div class="search-form search-form2">

								<input type="text" value="Enter your keyword..." onfocus="if (this.value==this.defaultValue) this.value = ''" onblur="if (this.value=='') this.value = this.defaultValue" />
								<input type="submit" value="" />
							</div> -->
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Header -->
		{% block content %}
		

		{% endblock %}
		<div id="footer">
			<div class="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="left-footer">
								<div class="logo-footer">
									<h2>FabulousD</h2>
								</div>
								<div class="contact-footer">
									<h2 class="title-footer">Contact Us</h2>
									<p><i class="fa fa-home"></i> Our business address is 9th floor, Eleganza Plaza, off Adeyemo Alakija street, Victoria Island, Lagos State.</p>
									<p><i class="fa fa-tablet"></i> + 234 818 6737 195</p>
									<p><i class="fa fa-envelope"></i> support@fabulousd.com</p>
								</div>
							</div>
						</div>
						<div class="col-md-8 col-sm-8 col-xs-12">
							<div class="right-footer">
								<div class="row">
									<div class="col-md-6 col-sm-6 col-xs-12">
										<h2 class="title-footer">Connect with Us</h2>
										<div class="social-footer">
											<ul>
												<li><a href="#"><i class="fa fa-facebook"></i></a></li>
												<li><a href="#"><i class="fa fa-twitter"></i></a></li>
												<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
												<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
												<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
												<li><a href="#"><i class="fa fa-youtube"></i></a></li>
												<li><a href="#"><i class="fa fa-share-alt"></i></a></li>
											</ul>
										</div>
									</div>
									<div class="col-md-6 col-sm-6 col-xs-12">
										<h2 class="title-footer">Newsletter</h2>
										<div class="news-letter-form">
											<form>
												<input type="text" value="Enter your Email..." onfocus="if (this.value==this.defaultValue) this.value = ''" onblur="if (this.value=='') this.value = this.defaultValue" />
												<input type="submit" value="Subscribe" />
											</form>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-4 colsm-4 col-xs-12">
										<div class="box-footer-menu">
											<h2 class="title-footer">My account</h2>
											<ul class="menu-footer-default">
												<li><a href="#">My orders</a></li>
												<li><a href="#">My credit slips</a></li>
												<li><a href="#">My addresses</a></li>
												<li><a href="#">My personal info</a></li>
											</ul>
										</div>
									</div>
									<div class="col-md-4 colsm-4 col-xs-12">
										<div class="box-footer-menu">
											<h2 class="title-footer">INFORMATION</h2>
											<ul class="menu-footer-default">
												<li><a href="#">About Us</a></li>
												<li><a href="#">Terms of Use</a></li>
												<li><a href="#">Club Info and FAQ's</a></li>
												<li><a href="#">Privacy Policy</a></li>
												<li><a href="#">Contact Us</a></li>
											</ul>
										</div>
									</div>
									<div class="col-md-4 colsm-4 col-xs-12">
										<div class="box-footer-menu">
											<h2 class="title-footer">Customer Service</h2>
											<ul class="menu-footer-default">
												<li><a href="#">Ask in forum</a></li>
												<li><a href="#">Help Desk</a></li>
												<li><a href="#">Payment Methods</a></li>
												<li><a href="#">Custom Work</a></li>
												<li><a href="#">Promotions</a></li>
											</ul>
										</div>
									</div>
									<div class="row">
										<div class="col-md-6 col-sm-6 col-xs-12">
											<div class="payment-method">
												<ul class="list-inline text-right">
													<li><a href="#"><img src="{% static 'images/home12/payment1.png' %}" alt="" /></a></li>
													<li><a href="#"><img src="{% static 'images/home12/payment2.png' %}" alt="" /></a></li>
													<li><a href="#"><img src="{% static 'images/home12/payment3.png' %}" alt="" /></a></li>
													<li><a href="#"><img src="{% static 'images/home12/payment4.png' %}" alt="" /></a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
		<!-- End Footer -->
	</div>
	<script type="text/javascript" src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.fancybox.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.hoverdir.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/modernizr.custom.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.jcarousellite.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/theme.js' %}"></script>
	{% block js %} {% endblock %}
</body>
</html>

templates/product_cart.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}FabulousD | Catalog{% endblock %}

{% block style %}

    <link type="text/css" href="{% static 'style/css/style-main.css' %}" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Sevillana"> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}" media="all"/>

    <!-- Google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>
    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="{% static 'css/cart/boostrap.css' %}">
    <!-- Font Awesome styles (icons) -->
    <link rel="stylesheet" href="{% static 'css/cart/font_awesome.css' %}">
    <!-- Main Template styles -->
    <link rel="stylesheet" href="{% static 'css/cart/styles.css' %}">
    <!-- IE 8 Fallback -->
    <!--[if lt IE 9]>
	<link rel="stylesheet" type="text/css" href="{% static 'css/ie.css' %}" />
<![endif]-->

    <!-- Your custom styles (blank file) -->
    <link rel="stylesheet" href="{% static 'css/cart/mystyles.css' %}">

{% endblock %}

{% block content %}
<br>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    
                    {% if empty %}
                        <h1>{{ empty_message }}</h1>
                    {% else %}
                        <table class="table cart-table">
                            <thead>
                                <tr>
                                    <th>Item</th>
                                    <th>Name</th>
                                    <th>QTY</th>
                                    <th>Price</th>
                                    <th>Variations</th>
                                    <th>Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart.cartitem_set.all %}
                                    <tr>
                                        <td class="cart-item-image">
                                            <a href="{{ item.product.productimage_set.first.image.url }}">
                                                <img height="70" width="70" src="{{ item.product.productimage_set.first.image.url }}" alt="Image Alternative text" title="AMaze" />
                                            </a>
                                        </td>
                                        <td><a href="{% url 'products:product_detail' item.product.slug %}">{{ item.product }}</a>
                                        </td>
                                        <td> {{ item.quantity }} </td>
                                        <td>${{ item.product.price }}</td>
                                        <td>${{ item.variations.all }}</td>
                                        <td class="cart-item-remove">
                                            <a class="fa fa-times" href="{% url 'carts:remove_from_cart' item.id %}"></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                         </table>    <a href="#" class="btn btn-primary">Update the cart</a>
                    {% endif %}

                </div>
                <div class="col-md-3">
                    <ul class="cart-total-list">
                        <li><span>Sub Total</span><span>${{ cart.total_price }}</span>
                        </li>
                        <li><span>Shipping</span><span>$0.00</span>
                        </li>
                        <li><span>Taxes</span><span>$0.00</span>
                        </li>
                        <li><span>Total</span><span>${{ cart.total_price }}</span>
                        </li>
                    </ul>
                    <a href="{% url 'orders:check_out' %}" class="btn btn-primary btn-lg">Checkout</a>
                </div>
            </div>
            <div class="gap"></div>
        </div>

{% endblock %}


{% block js %}
        <!-- Scripts queries -->
        <script src="{% static 'js/cart/jquery.js' %}"></script>
        <script src="{% static 'js/cart/boostrap.min.js' %}"></script>
        <script src="{% static 'js/cart/countdown.min.js' %}"></script>
        <script src="{% static 'js/cart/flexnav.min.js' %}"></script>
        <script src="{% static 'js/cart/magnific.js' %}"></script>
        <script src="{% static 'js/cart/tweet.min.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
        <script src="{% static 'js/cart/fitvids.min.js' %}"></script>
        <script src="{% static 'js/cart/mail.min.js' %}"></script>
        <script src="{% static 'js/cart/ionrangeslider.js' %}"></script>
        <script src="{% static 'js/cart/icheck.js' %}"></script>
        <script src="{% static 'js/cart/fotorama.js' %}"></script>
        <script src="{% static 'js/cart/card-payment.js' %}"></script>
        <script src="{% static 'js/cart/owl-carousel.js' %}"></script>
        <script src="{% static 'js/cart/masonry.js' %}"></script>
        <script src="{% static 'js/cart/nicescroll.js' %}"></script>

{% endblock %}